version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erab_web
    volumes:
      - ./app:/var/www/html
    networks:
      - shared-net
    expose:
      - 80

  nginx:
    image: nginx:alpine
    container_name: erab_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/var/www/html
    ports:
      - "3438:80"
    depends_on:
      - web
    networks:
      - shared-net

networks:
  shared-net:
    external: true

volumes:
  dbdata:
